# Generated by Django 4.2 on 2023-04-16 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=11, unique=True)),
                ('company_name', models.CharField(max_length=50)),
                ('company_addr', models.CharField(max_length=100)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('opt1', 'Установить экобокс'), ('opt2', 'Вывезти мусор'), ('opt3', 'Демонтировать экобокс')], max_length=30)),
                ('comments', models.CharField(blank=True, max_length=150)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('opt', 'new'), ('opt2', 'in progress'), ('opt3', 'completed')], max_length=30)),
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name2', models.CharField(max_length=30)),
                ('participants', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
